### ISSUE TITLE
I get an error with version 3.0.0, 

### ISSUE THREAD

**Issue by amolpatilnn** [imirzov/ccx2paraview#21]
I executed following command with version 3.0.0,
ccx2paraview.exe exp_calculix.frd vtu

It gave me following error.

Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

However everything was working fine in earlier version-2.3.1.

Please help.

**Comment by imirzov** [comment]
Hi,

The problem is definitely not in the source code, because I do not use any 'encodings' module. Maybe windows binary is corrupt - I used nuitka - a new tool to generate binaries. Please, try to run the converter from [source code](https://github.com/calculix/ccx2paraview/archive/refs/tags/v3.0.0.zip). Use Python 3. Read [how to run converter from source code](https://github.com/calculix/ccx2paraview#for-developers). Instal dependancies with command:
`pip3 install numpy vtk ccx2paraview`

Run converter with command:
`python3 ccx2paraview.py exp_calculix.frd vtu`

Also pay attention to .frd-file type - it should be ASCII, not binary.
