### ISSUE TITLE
Using ParaViewWeb

### ISSUE THREAD

**Issue by feacluster** [imirzov/ccx2paraview#22]
Your translator looks very cool! I want to post-process small models in the web browser. I think ParaViewWeb can do that. Have you ever tried setting that up? If not, do you think it will work with your vtk files?

Presently I do some basic screenshots from cgx via a batch file. See:

https://www.feacluster.com/web_calculix.php

I want to enhance that to allow people to do full 3d visualization over the web.

**Comment by imirzov** [comment]
Hi, thank you for using the converter. I have never tried ParaViewWeb, but it definitely will work with VTK files, since VTK is a native KitWare format.
Your CalculiX cluster looks very promising. Please, have a look on simscale.com - that's what you can grow up to. May I also ask a question? I wonder if you have any supporter/sponsor for your project? Building up a server + domain name should cost something - who pays for that?

**Comment by feacluster** [comment]
Thanks, I will look into paravieweb and let you know when you can test it out.  For now this is just a hobby. Thankfully domains and servers are cheap. In fact google/azure/Amazon all offer one free instance which is enough for doing quite a bit :-)
